# Generated by Django 4.2.8 on 2023-12-17 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('g_mtg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'client_id',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='ID клиента из сторонних ресурсов',
                    ),
                ),
                (
                    'source_client_info',
                    models.CharField(
                        max_length=255,
                        verbose_name='Источник информации о клиенте',
                    ),
                ),
                (
                    'client_data',
                    models.JSONField(verbose_name='Данные о клиенте'),
                ),
                (
                    'client_data_decoding',
                    models.JSONField(
                        verbose_name='Расшифровка данных о клиенте'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ok', 'Ок'),
                            ('error', 'Ошибка'),
                            ('initial', 'Исходный'),
                            ('in_progress', 'В процессе'),
                        ],
                        default='initial',
                        max_length=255,
                        verbose_name='Статус запроса',
                    ),
                ),
                (
                    'success_type',
                    models.CharField(
                        choices=[
                            ('sold', 'Продано'),
                            ('reflection', 'Обдумывание'),
                            ('interest', 'Заинтересованность'),
                            ('negative_reaction', 'Негативная реакция'),
                            ('positive_reaction', 'Позитивная реакция'),
                            ('undefined', 'Не определено'),
                        ],
                        default='undefined',
                        max_length=255,
                        verbose_name='Тип успеха',
                    ),
                ),
                (
                    'project_sale_channel',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='users_requests',
                        to='g_mtg.projectsalechannel',
                        verbose_name='Канал связи проекта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Данные для запроса',
                'verbose_name_plural': 'Данные для запросов',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                ('text', models.TextField(verbose_name='Сообщение')),
                (
                    'message_type',
                    models.CharField(
                        choices=[
                            ('user', 'Пользовательское'),
                            ('system', 'Системное'),
                        ],
                        max_length=255,
                        verbose_name='Тип сообщения',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ok', 'Данные сформирован хорошо'),
                            ('error', 'Ошибка при формировании данных'),
                            ('revision', 'Доработка сформированных данных'),
                            ('undefined', 'Не определено'),
                        ],
                        default='undefined',
                        max_length=255,
                        verbose_name='Статус сообщения',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parents',
                        to='llm_request.message',
                        verbose_name='Родительское сообщение',
                    ),
                ),
                (
                    'request_data',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='llm_request.requestdata',
                        verbose_name='Данные для запроса',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='requestdata',
            constraint=models.UniqueConstraint(
                fields=('project_sale_channel', 'client_data'),
                name='unique_client_data_for_project_sale_channel',
            ),
        ),
        migrations.AddConstraint(
            model_name='requestdata',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'success_type__in',
                        [
                            'sold',
                            'reflection',
                            'interest',
                            'negative_reaction',
                            'positive_reaction',
                            'undefined',
                        ],
                    )
                ),
                name='request_data_success_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='requestdata',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('status__in', ['ok', 'error', 'initial', 'in_progress'])
                ),
                name='request_data_status_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(
                check=models.Q(('message_type__in', ['user', 'system'])),
                name='message_message_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('status__in', ['ok', 'error', 'revision', 'undefined'])
                ),
                name='message_message_status_valid',
            ),
        ),
    ]
