# Generated by Django 4.2.8 on 2023-12-17 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('llm_request', '0002_fakeclientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(
                choices=[
                    ('ok', 'Данные сформированы хорошо'),
                    ('error', 'Ошибка при формировании данных'),
                    ('revision', 'Доработка сформированных данных'),
                    ('undefined', 'Не определено'),
                ],
                default='undefined',
                max_length=255,
                verbose_name='Статус сообщения',
            ),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
