# Generated by Django 4.2.8 on 2023-12-16 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        upload_to='media',
                        verbose_name='Картинка продукта',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'key_name',
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name='Ключ продукта',
                    ),
                ),
                ('description', models.TextField(verbose_name='Описание')),
                (
                    'link',
                    models.URLField(
                        blank=True, verbose_name='Ссылка на продукт'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Описание'),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects',
                        to='g_mtg.product',
                        verbose_name='Продукт банка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SaleChannel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        upload_to='media',
                        verbose_name='Картинка канала',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'key_name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Ключ канала'
                    ),
                ),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Канал продажи',
                'verbose_name_plural': 'Каналы продаж',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('manager', 'Руководитель'),
                            ('performer', 'Исполнитель'),
                        ],
                        default='performer',
                        max_length=255,
                        verbose_name='Роль в проекте',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects_users',
                        to='g_mtg.project',
                        verbose_name='Проект',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects_users',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пользователь, участвующий в проекте',
                'verbose_name_plural': 'Пользователи, участвующие в проектах',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectSaleChannel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'prompt',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Подсказка для генерации продукта',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects_sales_channels',
                        to='g_mtg.project',
                        verbose_name='Продукт банка',
                    ),
                ),
                (
                    'sale_channel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='projects_sales_channels',
                        to='g_mtg.salechannel',
                        verbose_name='Канал продаж',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Канал продажи в проекте',
                'verbose_name_plural': 'Каналы продаж в проектах',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_channels',
            field=models.ManyToManyField(
                blank=True,
                related_name='projects',
                through='g_mtg.ProjectSaleChannel',
                to='g_mtg.salechannel',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(
                blank=True,
                related_name='projects',
                through='g_mtg.ProjectUser',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='projectuser',
            constraint=models.UniqueConstraint(
                fields=('project', 'user'), name='unique_user_for_project'
            ),
        ),
        migrations.AddConstraint(
            model_name='projectuser',
            constraint=models.CheckConstraint(
                check=models.Q(('role__in', ['manager', 'performer'])),
                name='project_user_role_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='projectsalechannel',
            constraint=models.UniqueConstraint(
                fields=('project', 'sale_channel'),
                name='unique_sale_channel_for_project',
            ),
        ),
    ]
