# Generated by Django 4.2.8 on 2023-12-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_mtg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='projects_users',
                to='g_mtg.project',
                verbose_name='Проект',
            ),
        ),
    ]
