# Generated by Django 4.2.8 on 2023-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_mtg', '0003_product_image_product_link_salechannel_image'),
    ]

    operations = [
        migrations.RemoveField(model_name='project', name='prompt',),
        migrations.AddField(
            model_name='projectsalechannel',
            name='prompt',
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name='Подсказка для генерации продукта',
            ),
        ),
    ]
