# Generated by Django 4.2.8 on 2023-12-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.UniqueConstraint(
                fields=('project_sale_channel', 'client_data'),
                name='unique_client_data_for_project_sale_channel',
            ),
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'success_type__in',
                        [
                            'sold',
                            'reflection',
                            'interest',
                            'negative_reaction',
                            'positive_reaction',
                            'undefined',
                        ],
                    )
                ),
                name='user_request_success_type_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='userrequest',
            constraint=models.CheckConstraint(
                check=models.Q(('status__in', ['ok', 'error', 'in_progress'])),
                name='user_request_status_valid',
            ),
        ),
    ]
